version: '3'
services:
  prometheus:
    container_name: prometheus
    image: prom/prometheus
    ports: [ "9090:9090" ]
    volumes:
    - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro

  grafana:
    container_name: grafana
    image: grafana/grafana
    ports: [ "3000:3000" ]
    volumes:
    - ./grafana/provisioning:/etc/grafana/provisioning:ro
    - ./grafana/config.ini:/etc/grafana/grafana.ini:ro
    - ./grafana/dashboards:/var/lib/grafana/dashboards:ro
