global:
  scrape_interval: 10s
  scrape_timeout: 10s

scrape_configs:
  - job_name: psi
    static_configs:
    - targets: ['host.docker.internal:9000']
  - job_name: node
    static_configs:
    - targets: ['host.docker.internal:9001']

