{
 "title": "Linux PSI",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "type",
    "label": "Type",
    "query": "label_values(psi_memory_avg10,type)"
   }
  ]
 },
 "panels": [
  { "title": "Traditional Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Cores",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count(count(node_cpu_seconds_total) without (mode)) without (cpu)"
    }
   ]
  },
  {
   "title": "CPU Utilization",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 3 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(irate(node_cpu_seconds_total{mode=\"user\"}[1m]))",
     "legendFormat": "user"
    },
    {
     "expr": "sum(irate(node_cpu_seconds_total{mode=\"system\"}[1m]))"
    }
   ]
  },
  {
   "title": "Load averages",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 3 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "node_load1", "legendFormat": "1m" },
    { "expr": "node_load5", "legendFormat": "5m" },
    { "expr": "node_load15", "legendFormat": "15m" }
   ]
  },
  {
   "title": "Processes",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "node_procs_blocked", "legendFormat": "blocked" },
    { "expr": "node_procs_running", "legendFormat": "running" }
   ]
  },
  {
   "title": "CPU",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU",
     "type": "graph",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 2 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      { "expr": "psi_cpu_avg10", "legendFormat": "avg10" },
      { "expr": "psi_cpu_avg60", "legendFormat": "avg60" },
      { "expr": "psi_cpu_avg300", "legendFormat": "avg300" }
     ]
    }
   ]
  },
  {
   "title": "Memory",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 },
   "collapsed": true,
   "panels": [
    {
     "title": "Some",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 3 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "psi_memory_avg10{type=\"some\"}",
       "legendFormat": "avg10"
      },
      {
       "expr": "psi_memory_avg60{type=\"some\"}",
       "legendFormat": "avg60"
      },
      {
       "expr": "psi_memory_avg300{type=\"some\"}",
       "legendFormat": "avg300"
      }
     ]
    },
    {
     "title": "Full",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 3 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "psi_memory_avg10{type=\"full\"}",
       "legendFormat": "avg10"
      },
      {
       "expr": "psi_memory_avg60{type=\"full\"}",
       "legendFormat": "avg60"
      },
      {
       "expr": "psi_memory_avg300{type=\"full\"}",
       "legendFormat": "avg300"
      }
     ]
    }
   ]
  },
  {
   "title": "IO",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 },
   "collapsed": true,
   "panels": [
    {
     "title": "Some",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 31 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "psi_io_avg10{type=\"some\"}",
       "legendFormat": "avg10"
      },
      {
       "expr": "psi_io_avg60{type=\"some\"}",
       "legendFormat": "avg60"
      },
      {
       "expr": "psi_io_avg300{type=\"some\"}",
       "legendFormat": "avg300"
      }
     ]
    },
    {
     "title": "Full",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 31 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "psi_io_avg10{type=\"full\"}",
       "legendFormat": "avg10"
      },
      {
       "expr": "psi_io_avg60{type=\"full\"}",
       "legendFormat": "avg60"
      },
      {
       "expr": "psi_io_avg300{type=\"full\"}",
       "legendFormat": "avg300"
      }
     ]
    }
   ]
  }
 ]
}